# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5338d163ff267679249dc1ea06afb5ec56e3ea88d4a6da3e7fbf3de9fcfa49e83f935916f4d3b603a771407653bd43255b7ecb6725ab411219a78ce137a145e

test:
  secret_key_base: 7e82f54d74c9330c091be068a4238d0cfceed447cd9ce5d454222039447fa483a5c326b8ad2453c3f50bf891c98afc1020f7c7475aa5f7e836f0d68a69c86878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
